####  CONFIGURATION SPECIFIC ####
hostname: AWS-CSR-01

default_route: 100.10.9.6

l3_interfaces:
  - interface_type: GigabitEthernet
    interface_id: 1
    description: Internet uplink
    shutdown: false
    ipv4_address: 100.10.9.5/30

  - interface_type: Loopback
    interface_id: 0
    description: AWS network
    ipv4_address: 10.10.10.254/24
    shutdown: false

  - interface_type: Tunnel
    interface_id: 100
    description: DMVPN
    ipv4_address: 192.168.100.3/24
    source: GigabitEthernet1
    mode: gre multipoint
    shutdown: false
