---
- name: Render a Jinja2 template for common FHRP parameters onto an {{ ansible_network_os | upper }} device
  cisco.ios.ios_config: 
    src: "{{ansible_network_os | lower}}_fhrp_common_config.j2"