####  CONNECTION SPECIFIC ####
ansible_user: "{{ lookup('env','VIRL2_NODES_USER') }}"
ansible_ssh_pass: "{{ lookup('env','VIRL2_NODES_PASS') }}"

ansible_port: 22
ansible_network_os: ios
ansible_connection: network_cli

ansible_ssh_common_args: "{{ lookup('env','ANSIBLE_PROXY_COMMAND') }}"

####  CONFIGURATION SPECIFIC ####
